import type { SecurityToolMetadata } from "../core/types.ts";

export const SECURITY_TOOL_CATALOG: readonly SecurityToolMetadata[] = [
	{
		name: "security_state",
		aliases: [],
		category: "internal",
		baseRisk: "P0",
		scopeMode: "none",
		capabilities: ["state.read", "state.write", "evidence.record"],
		preconditions: [],
		postconditions: ["security state remains replayable from session events"],
		recommendedAgents: ["coordinator", "sec-recon", "sec-web", "sec-analysis", "sec-response"],
		description: "Maintain explicit SecAgent task state, evidence, hypotheses, findings, and stage.",
	},
	{
		name: "security_scope",
		aliases: [],
		category: "internal",
		baseRisk: "P0",
		scopeMode: "none",
		capabilities: ["scope.read", "scope.write"],
		preconditions: ["scope changes must reflect user or competition authorization"],
		postconditions: ["authorized targets are explicit and auditable"],
		recommendedAgents: ["coordinator"],
		description: "Define the explicit authorized target boundary for network actions.",
	},
	{
		name: "security_decide",
		aliases: [],
		category: "internal",
		baseRisk: "P0",
		scopeMode: "none",
		capabilities: ["decision.rank", "decision.record"],
		preconditions: ["at least two meaningful candidate actions"],
		postconditions: ["ranked decision is stored in the replayable state"],
		recommendedAgents: ["coordinator", "sec-recon", "sec-web", "sec-analysis", "sec-response"],
		description: "Rank candidate next actions with registry-derived risk floors.",
	},
	{
		name: "security_tools",
		aliases: [],
		category: "internal",
		baseRisk: "P0",
		scopeMode: "none",
		capabilities: ["tool.registry.read"],
		preconditions: [],
		postconditions: [],
		recommendedAgents: ["coordinator", "sec-recon", "sec-web", "sec-analysis", "sec-response"],
		description: "Inspect the structured security-tool registry used by policy and planning.",
	},
	{
		name: "read",
		aliases: [],
		category: "local",
		baseRisk: "P0",
		scopeMode: "none",
		capabilities: ["filesystem.read"],
		preconditions: [],
		postconditions: ["local file content observed"],
		recommendedAgents: ["sec-analysis", "sec-response"],
		description: "Read local files without modifying them.",
	},
	{
		name: "grep",
		aliases: [],
		category: "local",
		baseRisk: "P0",
		scopeMode: "none",
		capabilities: ["filesystem.search"],
		preconditions: [],
		postconditions: ["matching local evidence identified"],
		recommendedAgents: ["sec-analysis"],
		description: "Search local text content.",
	},
	{
		name: "find",
		aliases: [],
		category: "local",
		baseRisk: "P0",
		scopeMode: "none",
		capabilities: ["filesystem.enumerate"],
		preconditions: [],
		postconditions: ["candidate local artifacts enumerated"],
		recommendedAgents: ["sec-analysis"],
		description: "Enumerate local filesystem paths.",
	},
	{
		name: "ls",
		aliases: [],
		category: "local",
		baseRisk: "P0",
		scopeMode: "none",
		capabilities: ["filesystem.enumerate"],
		preconditions: [],
		postconditions: ["directory contents observed"],
		recommendedAgents: ["sec-analysis"],
		description: "List local directory contents.",
	},
	{
		name: "edit",
		aliases: [],
		category: "response",
		baseRisk: "P2",
		scopeMode: "none",
		capabilities: ["filesystem.modify"],
		preconditions: ["change is authorized", "rollback or recovery path is understood"],
		postconditions: ["modified artifact must be validated"],
		recommendedAgents: ["sec-response"],
		description: "Modify an existing local file.",
	},
	{
		name: "write",
		aliases: [],
		category: "response",
		baseRisk: "P2",
		scopeMode: "none",
		capabilities: ["filesystem.modify"],
		preconditions: ["change is authorized", "destination is not protected"],
		postconditions: ["written artifact must be validated"],
		recommendedAgents: ["sec-response"],
		description: "Create or replace a local file.",
	},
	{
		name: "bash",
		aliases: [],
		category: "shell",
		baseRisk: "P1",
		scopeMode: "dynamic",
		capabilities: ["process.execute"],
		preconditions: ["nested commands are evaluated by the SecAgent registry and policy"],
		postconditions: ["command result is captured in the audit timeline"],
		recommendedAgents: ["coordinator", "sec-recon", "sec-web", "sec-analysis", "sec-response"],
		description: "Execute a local shell command; effective risk is derived from nested executables.",
	},
	{
		name: "curl",
		aliases: [],
		category: "network",
		baseRisk: "P1",
		scopeMode: "network-target",
		capabilities: ["network.http.request"],
		preconditions: ["target is within authorized scope"],
		postconditions: ["HTTP response becomes an observation, not automatically a finding"],
		recommendedAgents: ["sec-recon", "sec-web"],
		description: "Issue HTTP(S) requests to an authorized target.",
	},
	{
		name: "wget",
		aliases: [],
		category: "network",
		baseRisk: "P1",
		scopeMode: "network-target",
		capabilities: ["network.http.request", "artifact.download"],
		preconditions: ["target is within authorized scope"],
		postconditions: ["downloaded artifact should be recorded before analysis"],
		recommendedAgents: ["sec-recon", "sec-web", "sec-analysis"],
		description: "Fetch an authorized network resource.",
	},
	{
		name: "httpx",
		aliases: [],
		category: "recon",
		baseRisk: "P1",
		scopeMode: "network-target",
		capabilities: ["network.http.probe", "service.fingerprint"],
		preconditions: ["target is within authorized scope"],
		postconditions: ["service observations are recorded with confidence"],
		recommendedAgents: ["sec-recon", "sec-web"],
		description: "Probe authorized HTTP services and collect fingerprints.",
	},
	{
		name: "nmap",
		aliases: [],
		category: "recon",
		baseRisk: "P2",
		scopeMode: "network-target",
		capabilities: ["network.port_scan", "service.fingerprint"],
		preconditions: ["target is within authorized scope", "scan intensity is appropriate for the task"],
		postconditions: ["ports and service fingerprints are recorded as observations"],
		recommendedAgents: ["sec-recon"],
		description: "Actively enumerate ports and services on authorized targets.",
	},
	{
		name: "masscan",
		aliases: [],
		category: "recon",
		baseRisk: "P2",
		scopeMode: "network-target",
		capabilities: ["network.port_scan.high_rate"],
		preconditions: ["target is within authorized scope", "rate limit is appropriate for the environment"],
		postconditions: ["discovered ports require follow-up validation"],
		recommendedAgents: ["sec-recon"],
		description: "Perform high-rate port discovery within explicit scope.",
	},
	{
		name: "nuclei",
		aliases: [],
		category: "web",
		baseRisk: "P2",
		scopeMode: "network-target",
		capabilities: ["vulnerability.template_probe", "network.http.probe"],
		preconditions: ["target is within authorized scope", "template set is appropriate"],
		postconditions: ["scanner output must be verified before becoming a confirmed finding"],
		recommendedAgents: ["sec-web"],
		description: "Run template-based checks against authorized targets.",
	},
	{
		name: "ffuf",
		aliases: [],
		category: "web",
		baseRisk: "P2",
		scopeMode: "network-target",
		capabilities: ["web.content_discovery"],
		preconditions: ["target is within authorized scope", "request rate is bounded"],
		postconditions: ["discovered routes are recorded as observations"],
		recommendedAgents: ["sec-web"],
		description: "Perform bounded web content discovery.",
	},
	{
		name: "gobuster",
		aliases: [],
		category: "web",
		baseRisk: "P2",
		scopeMode: "network-target",
		capabilities: ["web.content_discovery", "dns.enumeration"],
		preconditions: ["target is within authorized scope", "enumeration mode is authorized"],
		postconditions: ["discovered routes or names are recorded as observations"],
		recommendedAgents: ["sec-web", "sec-recon"],
		description: "Enumerate authorized web paths or DNS names.",
	},
	{
		name: "dirsearch",
		aliases: [],
		category: "web",
		baseRisk: "P2",
		scopeMode: "network-target",
		capabilities: ["web.content_discovery"],
		preconditions: ["target is within authorized scope", "request rate is bounded"],
		postconditions: ["discovered routes are recorded as observations"],
		recommendedAgents: ["sec-web"],
		description: "Enumerate authorized web paths.",
	},
	{
		name: "nikto",
		aliases: [],
		category: "web",
		baseRisk: "P2",
		scopeMode: "network-target",
		capabilities: ["web.misconfiguration_probe", "web.vulnerability_probe"],
		preconditions: ["target is within authorized scope"],
		postconditions: ["scanner output must be independently validated"],
		recommendedAgents: ["sec-web"],
		description: "Probe an authorized web service for known risky configurations and exposures.",
	},
	{
		name: "wpscan",
		aliases: [],
		category: "web",
		baseRisk: "P2",
		scopeMode: "network-target",
		capabilities: ["web.cms.enumerate", "web.vulnerability_probe"],
		preconditions: ["target is within authorized scope"],
		postconditions: ["reported issues require evidence-based verification"],
		recommendedAgents: ["sec-web"],
		description: "Assess an authorized WordPress surface.",
	},
	{
		name: "sqlmap",
		aliases: [],
		category: "web",
		baseRisk: "P3",
		scopeMode: "network-target",
		capabilities: ["web.injection.verify"],
		preconditions: ["target is within authorized scope", "intrusive verification is explicitly justified"],
		postconditions: ["results and side effects must be reviewed"],
		recommendedAgents: ["sec-web"],
		description: "Perform intrusive SQL injection verification on an authorized target.",
	},
	{
		name: "hydra",
		aliases: [],
		category: "network",
		baseRisk: "P3",
		scopeMode: "network-target",
		capabilities: ["authentication.verify.high_rate"],
		preconditions: ["target is within authorized scope", "credential testing is explicitly authorized"],
		postconditions: ["authentication impact and lockout risk must be reviewed"],
		recommendedAgents: ["sec-recon", "sec-web"],
		description: "Perform high-risk authentication verification within explicit authorization.",
	},
	{
		name: "ssh",
		aliases: [],
		category: "network",
		baseRisk: "P2",
		scopeMode: "network-target",
		capabilities: ["network.remote_session"],
		preconditions: ["target is within authorized scope", "credentials or access path are authorized"],
		postconditions: ["remote actions remain subject to policy and audit"],
		recommendedAgents: ["sec-response", "sec-analysis"],
		description: "Open an authorized remote shell session.",
	},
	{
		name: "scp",
		aliases: ["sftp"],
		category: "network",
		baseRisk: "P2",
		scopeMode: "network-target",
		capabilities: ["network.remote_file_transfer"],
		preconditions: ["target is within authorized scope", "file transfer is authorized"],
		postconditions: ["transferred artifacts are tracked"],
		recommendedAgents: ["sec-analysis", "sec-response"],
		description: "Transfer files to or from an authorized remote target.",
	},
	{
		name: "nc",
		aliases: ["netcat"],
		category: "network",
		baseRisk: "P2",
		scopeMode: "network-target",
		capabilities: ["network.raw_connection"],
		preconditions: ["target is within authorized scope"],
		postconditions: ["raw network interaction is audited"],
		recommendedAgents: ["sec-recon", "sec-analysis"],
		description: "Create a raw network connection to an authorized target.",
	},
	{
		name: "msfconsole",
		aliases: ["metasploit"],
		category: "network",
		baseRisk: "P3",
		scopeMode: "network-target",
		capabilities: ["vulnerability.exploit.verify"],
		preconditions: ["target is within authorized scope", "exploit verification is explicitly authorized"],
		postconditions: ["effects and evidence must be reviewed immediately"],
		recommendedAgents: ["sec-web", "sec-response"],
		description: "Run high-risk exploit verification against an explicitly authorized target.",
	},
] as const;
